services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    container_name: nameral-dragonfly
    ports:
      - "6379:6379"
    volumes:
      - nameral-dragonfly-data:/data
    command: --dbfilename= --cache_mode --maxmemory 512M
    ulimits:
      memlock: -1
    cpus: 2.0
    mem_limit: 2G
    memswap_limit: 2G
    restart: no
    logging:
      driver: none

volumes:
  nameral-dragonfly-data: